### PR TITLE
Adds the breakable bottles environment

### PR DESCRIPTION
**Pull request by rk1a**
Adds the breakable bottles environment which is used in [Vamplew et al. 2021](https://doi.org/10.1016/j.engappai.2021.104186) as a toy model for irreversible change in stochastic environments.

I wasn't really planning for creating a pull request, so the commit history is a bit messy...

### CODE REVIEW

**Comment by LucasAlegre** [comment]
Hi, thank you very much for the contribution! Would you mind checking/fixing the test errors? Also, if you also could add a description of the env in the table in the README it would be awesome :)

**Comment by rk1a** [comment]
Hi,
the error comes from a bug in gym 0.24 (https://github.com/openai/gym/issues/2956) because I use a Dict observation space.
They fixed it in 0.25.1 but I saw in your setup.py that mo-gym is not compatible with this version (yet).
So I guess we can wait with this until this incompatibility has been resolved?
As far as I can tell the only env that is breaking is MOMountainCar due to an assertion error related to the render mode.

------- Original Message -------

**Comment by LucasAlegre** [comment]
I commented the test for the env because of gym's bug. This should be fixed later when we support a newer version of gym.
@rk1a can you please whether my description of the env in the README is accurate?

**Comment by rk1a** [comment]
@LucasAlegre if you want you could add a little more detail regarding the potential-based reward "While carrying multiple bottles there is a small probability of dropping them. A potential-based penalty is applied for bottles left on the ground."

**Pull request merged**
